export default {
  login: 'JorgeFPeres',
  id: 77127673,
  node_id: 'MDQ6VXNlcjc3MTI3Njcz',
  avatar_url: 'https://avatars.githubusercontent.com/u/77127673?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/JorgeFPeres',
  html_url: 'https://github.com/JorgeFPeres',
  followers_url: 'https://api.github.com/users/JorgeFPeres/followers',
  following_url:
    'https://api.github.com/users/JorgeFPeres/following{/other_user}',
  gists_url: 'https://api.github.com/users/JorgeFPeres/gists{/gist_id}',
  starred_url:
    'https://api.github.com/users/JorgeFPeres/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/JorgeFPeres/subscriptions',
  organizations_url: 'https://api.github.com/users/JorgeFPeres/orgs',
  repos_url: 'https://api.github.com/users/JorgeFPeres/repos',
  events_url: 'https://api.github.com/users/JorgeFPeres/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/JorgeFPeres/received_events',
  type: 'User',
  site_admin: false,
  name: 'Jorge Fernando Peres',
  company: 'Unicesumar',
  blog: 'www.instagram.com/jorgef.peres',
  location: 'Curitiba - PR, Brazil',
  email: null,
  hireable: true,
  bio: 'Software Engineer Student\r\n',
  twitter_username: 'jorgefperes',
  public_repos: 34,
  public_gists: 3,
  followers: 1128,
  following: 139,
  created_at: '2021-01-07T21:52:59Z',
  updated_at: '2021-04-10T18:03:22Z',
}
